language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.12
  - DJANGO_VERSION=1.9.5
before_install:
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.22
    - python: "3.3"
      env: DJANGO_VERSION=1.4.22
      env: DJANGO_VERSION=1.9.5

